apiVersion: v1
kind: Service
metadata:
  name: sentinel-rainforest
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5050
    protocol: TCP
    targetPort: 5000
  selector:
    app: rainforest
    context: sentinel-services
    version: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-rainforest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rainforest
        context: sentinel-services
        version: v1
    spec:
      containers:
        -
          name: sentinel-rainforest
          image: docker.steventaylor.me/sentinel-rainforest-arm:latest
          imagePullPolicy: IfNotPresent
          env:
            -
              name: "PORT"
              value: "5000"
            -
              name: "CONSUL"
              value: "10.0.1.10"
          ports:
            -
              containerPort: 5000
              protocol: TCP